[project]
name = "multi-sig-study-vault"
version = "1.0.0"
clarity_version = 2

[contracts.finishing-line]
path = "src/finishing-line.clar"
clarity_version = 2

[contracts.dao-pool]
path = "src/dao-pool.clar"
clarity_version = 2
